name: CI/CD — develop → GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"    # adjust if you need a different Node LTS
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: npm run lint
        # remove or set continue-on-error: true if you don't want lint to block

      - name: Run unit tests (optional)
        run: npm test -- --watch=false --no-progress --browsers=ChromeHeadless
        # remove "|| true" to fail workflow on test failures; keep if you want non-blocking

      - name: Build (Angular production)
        # We force output into ./dist so deploy step is simple.
        run: |
          # For repository Pages (https://<user>.github.io/<repo>/) we set base-href
          # github.event.repository.name gives the repo name (e.g. "my-app")
          # If you host on a user/org site (username.github.io), change --base-href to "/"
          npx ng build --configuration production --output-path=dist --base-href="/${{ github.event.repository.name }}/"

      - name: Show built files
        run: ls -la dist || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # optional:
          # publish_branch: gh-pages       # default: gh-pages
          # keep_files: false              # remove files not in this commit (default false)
